### ISSUE TITLE
cp2code from inside a bash

### ISSUE THREAD

**Issue by byman64** [babakks/vscode-copy-from-terminal#19]
Maybe it's not a real issue but let me explain.

I created a little bash to show your what I mean:
code test_cp2code.sh

`#!/bin/sh
ps -aux | cp2code

chmod +x 
./test_cp2code.sh
line 2: cp2code: command not found
`
How I can use cp2code inside a bash script?

thx

**Comment by babakks** [comment]
The commands of this extension (i.e., `cp2code` or `tee2code`) only work when you open a new integrated shell (i.e., within VS Code's "Terminal" panel).

Of course, you can still pipe streams from external shells, with this native VS Code CLI command:

```sh
ps -aux | code -r -
```

or if you're using the Insiders version:

```sh
ps -aux | code-insiders -r -
```

(`-r` or `--resuse-window` flag prevents opening new VS Code windows per command execution)
